name: "Legitify Action"
description: "Legitify"
inputs:
  command:
    description: "command to run"
    required: false
    default: analyze
  github_token:
    description: "GitHub token"
    required: true
runs:
  using: "node16"
  main: "index.js"
